# fly.toml file generated for api-ecommerse on 2023-01-04T23:53:16+07:00

app = "api-ecommerse"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []



[deploy]
  release_command = "yarn db:sync"

[env]
  DATABASE_URL="postgres://api_ecommerse:he5pZeaULVPvL9F@top2.nearest.of.api-ecommerse-db.internal:5432"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
